USE Fichaje;

INSERT INTO Sesion VALUES(1, DATEADD(hour,2,GETDATE()), DATEADD(hour,2,GETDATE()));
INSERT INTO Sesion VALUES(1, DATEADD(hour,2,GETDATE()), DATEADD(hour,2,GETDATE()));
INSERT INTO Sesion VALUES(2, DATEADD(hour,2,GETDATE()), DATEADD(hour,2,GETDATE()));
INSERT INTO Sesion VALUES(2, DATEADD(hour,2,GETDATE()), DATEADD(hour,2,GETDATE()));
INSERT INTO Sesion VALUES(2, DATEADD(hour,2,GETDATE()), DATEADD(hour,2,GETDATE()));
INSERT INTO Sesion VALUES(3, DATEADD(hour,2,GETDATE()), DATEADD(hour,2,GETDATE()));
INSERT INTO Sesion VALUES(4, DATEADD(hour,2,GETDATE()), DATEADD(hour,2,GETDATE()));
INSERT INTO Sesion VALUES(4, DATEADD(hour,2,GETDATE()), DATEADD(hour,2,GETDATE()));
INSERT INTO Sesion VALUES(5, DATEADD(hour,2,GETDATE()), DATEADD(hour,2,GETDATE()));
INSERT INTO Sesion VALUES(5, DATEADD(hour,2,GETDATE()), DATEADD(hour,2,GETDATE()));