USE Fichaje;

CREATE TABLE Sesion(
Id INTEGER IDENTITY(1,1),
IdEmpleado INTEGER,
Fecha DATETIME,
CONSTRAINT Pk_Sesion PRIMARY KEY(Id),
CONSTRAINT Fk_Empleado_Sesion FOREIGN KEY (IdEmpleado) REFERENCES Empleado(Id) ON UPDATE CASCADE ON DELETE CASCADE
);